Refactored install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,126 @@
 #!/bin/bash
 
+####################################
+# Global variables
+####################################
+
 REQ_PYV="3.4"
 PYTHON_URI="https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz"
-# TODO: add verbosity
+TMPFILE=$(mktemp -u)
+TMPDIR=$(mktemp -d) # MacOS might require a template for `mkdir`. See manpages.
+
+####################################
+# Helper functions
+####################################
+
+function ask_yn {
+    : ''' Asks a yes or no question to the user.
+
+    This fnction should be used in conjuction with an if test.
+    For example,
+
+    :param question - $1: The question to ask the user
+    :return: 0 if the user .
+    '''
+    local question=$1
+    echo -e "$question [y/N]\c  "
+    read yn
+
+    if [[ $(grep -ix "$yn" <<< "y" ) ]]; then
+        return 0
+    fi
+    return 1
+}
+
+function exit_peacefully {
+    : '''Exits the script peacefully with an error code.
+
+    :param code - $1 (optional): The code to exit with. Defaults to 0.
+    '''
+    # Set $code equal to the first argument or 0.
+    local code=${1:=0}
+    cleanup_tmp
+    exit $code
+}
+
+function cleanup_tmp {
+    : '''Cleans up the temp files created when downloading python
+    from source.
+    '''
+    if [[ -f $TMPFILE ]]; then
+	    rm -rf $TMPFILE
+    fi
+    if [[ -d $TMPDIR ]]; then
+	    rm -rf $TMPDIR
+    fi
+}
+
+function cmd_exists {
+    : '''Check if a command exists. Similar to which, but is less
+    resource intensive and does not follow symlinks.
+
+    :param command - $1: the command to check
+    :returns: Wether the command exists
+    '''
+    if cmd_loc="$(command -v $1 2>&1)" && [[ -n $cmd_loc ]]; then
+        return 0
+    fi
+    return 1
+}
+
+function install_python_source {
+    : '''Installs python from source.
+    '''
+    if ask_yn "Would you like to try to download and install Python 3.7.1 from source? Requires make."; then
+        echo
+        echo "Downloading python source code..."
+
+        # TODO: maybe use curl
+        wget $PYTHON_URI -q --show-progress -O $TMPFILE
+
+
+        echo "Decompressing..."
+        # tar removes tmpfile
+        tar -C $TMPDIR --strip-components=1 -xzf $TMPFILE
+
+        if cmd_exists make; then
+            if cmd_exists gcc; then
+                pushd $TMPDIR >/dev/null
+                echo "Found $(make -v | head -1) and $(gcc --version | head -n 1). Configuring, compiling, and installing."
+                echo
+                echo "------------------------ [ CONFIGURING ] ------------------------"
+                echo
+                ./configure 2>&1 || { echo "\nCofiguring failed. Aborting install and cleaning up."; popd >/dev/null; exit_peacefully 1; }
+                echo
+                echo "------------------------ [ COMPILING ] ------------------------"
+                echo
+                make 2>&1 || { echo "\nCompile failed. Aborting install and cleaning up."; popd >/dev/null; exit_peacefully 1; }
+                echo
+                echo "------------------------ [ TESTING ] ------------------------"
+                echo
+                make test 2>&1 || { echo "\nTesting failed. Aborting install and cleaning up."; popd >/dev/null; exit_peacefully 1; }
+                echo
+                echo "------------------------ [ INSTALLING ] ------------------------"
+                echo
+                sudo make install 2>&1 || { echo "\Installing failed. Aborting install and cleaning up."; popd >/dev/null; exit_peacefully 1; }
+                popd >/dev/null
+                # Cleanup temp files, we no longer need them.
+                cleanup_tmp
+            else
+                echo "Cannot find gcc. Aborting install and cleaning up."
+                exit_peacefully 1
+            fi
+        else
+            echo "Cannot find make. Aborting install and cleaning up."
+            exit_peacefully 1
+        fi
+    fi
+}
+
+####################################
+# Start installation
+###################################
+
 echo "
     Copyright (C) 2018 Daniel Montgomery
 
@@ -14,95 +132,29 @@ echo "
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-    GNU General Public License for more details."
+    GNU General Public License for more details.
+"
 
-echo
-echo -e "Do you want to install codediff dependecies and utilities? [y/N]\c  "
-read install
-
-if [[ ! $(fgrep -ix "$install" <<< "y" ) ]]; then
+if ! ask_yn "Do you want to install codediff dependecies and utilities?"; then
     echo "Exiting installation script."
-    exit 0
+    exit_peacefully 1
 fi
 
-echo
-
-function cleanup { # $1 - tmpfile $2 - tmpdir
-    # TODO: make calling this easier. Passing args is error prone and annoying.
-    # cleanup temp files
-    if [ -f $1 ]; then
-	rm -rf $1
-    fi
-    if [ -d $2 ]; then
-	rm -rf $2
-    fi
-}
-
-function install_python_source {
-    echo -e "Would you like to try to download and install Python 3.7.1 from source? Requires make. [y/N]\c "
-    # TODO get python version from uri
-    read ipython
-
-    if [[ $(grep -ix "$ipython" <<< "y") ]]; then
-        tmpfile=$(mktemp -u)
-        tmpdir=$(mktemp -d) # MACOS might require a template for `mkdir`. See manpages.
-        echo
-        echo "Downloading python source code..."
-        # TODO: maybe use curl
-        wget $PYTHON_URI -q --show-progress -O $tmpfile
-        echo "Decompressing..."
-        # tar removes tmpfile
-        tar -C $tmpdir --strip-components=1 -xzf $tmpfile
-        if make_loc="$(command -v make 2>&1)" && [[ -n $make_loc ]]; then
-            if gcc_loc="$(command -v gcc 2>&1)" && [[ -n $gcc_loc ]]; then
-                pushd $tmpdir >dev/null
-                echo "Found $(make -v | head -1) and $(gcc --version | head -n 1). Configuring, compiling, and installing."
-                echo
-                echo "------------------------ [ CONFIGURING ] ------------------------"
-                echo
-                ./configure 2>&1 || { echo "\nCofiguring failed. Aborting install and cleaning up."; cleanup $tmpfile $tmpdir; popd >/dev/null; exit 1; }
-                echo
-                echo "------------------------ [ COMPILING ] ------------------------"
-                echo
-                make 2>&1 || { echo "\nCompile failed. Aborting install and cleaning up."; cleanup $tmpfile $tmpdir; popd >/dev/null; exit 1; }
-                echo
-                echo "------------------------ [ TESTING ] ------------------------"
-                echo
-                make test 2>&1 || { echo "\nTesting failed. Aborting install and cleaning up."; cleanup $tmpfile $tmpdir; popd >/dev/null; exit 1; }
-                echo
-                echo "------------------------ [ INSTALLING ] ------------------------"
-                echo
-                sudo make install 2>&1 || { echo "\Installing failed. Aborting install and cleaning up."; cleanup $tmpfile $tmpdir; popd >/dev/null; exit 1; }
-                popd >/dev/null
-            else
-                echo "Cannot find gcc. Aborting install and cleaning up."
-                cleanup $tmpfile $tmpdir
-                exit 1
-            fi
-        else
-            echo "Cannot find make. Aborting install and cleaning up."
-            cleanup $tmpfile $tmpdir
-            exit 1
-        fi
-    fi
-}
-
 # Check if they have the required version of python3. If they do not, try to build in from source.
-# TODO: make the conditional into a function.
-if python_loc="$(command -v python3 2>&1)" && [[ -n $python_loc ]]; then
-    if [ $(python3 -V 2>&1 | sed "s/.* \([0-9]\).\([0-9]\).*/\1\2/") -ge  ${REQ_PYV/./} ]; then
+if cmd_exists python3; then
+    if [[ $(python3 -V 2>&1 | sed "s/.* \([0-9]\).\([0-9]\).*/\1\2/") -ge  ${REQ_PYV/./} ]]; then
         # Good to go
-        echo "Your $(python3 -V 2>&1) distribution ($(command -v python3)) is up to date."
+        echo "Your $(python3 -V) distribution ($(command -v python3)) is up to date."
     else
         # python3 exists, needs updating
-        echo "Found $(python3 -V 2>&1) at $(command -v python3), but codediff requires at least Python $REQ_PYV."
+        echo "Found $(python3 -V) at $(command -v python3), but codediff requires at least Python $REQ_PYV."
         # TODO first try to install for apt if on debian
         install_python_source
+        echo "All dependencies installed, you can now run codediff!"
     fi
 else
     # Cannot find python3, install
     echo "Cannot find python3 in \$PATH."
     install_python_source
+    echo "All dependencies installed, you can now run codediff!"
 fi
-
-echo "All dependencies installed, you can now run CodeDiff!"
